import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "@/shared/style/globals.css";
import { Header } from "@/components/Header";

const geologica = Geologica({
  subsets: ["cyrillic"],
  variable: "--font-geologica",
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geologica.variable}>
        <Header />

        {children}
      </body>
    </html>
  );
}
